<?php
namespace GFPDF\Tests\Previewer;

use GFPDF\Plugins\Previewer\Validation\Token;

use WP_UnitTestCase;

/**
 * @package     Gravity PDF Previewer
 * @copyright   Copyright (c) 2020, Blue Liquid Designs
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU Public License
 * @since       1.0
 */

class TokenTest extends WP_UnitTestCase{

	public function setUp() {
		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function tearDown() {
		parent::tearDown(); // TODO: Change the autogenerated stub
	}
}