<?php

namespace GFPDF\Tests\Previewer;

use GFPDF\Plugins\Previewer\Validation\Token;

use WP_UnitTestCase;

/**
 * @package     Gravity PDF Previewer
 * @copyright   Copyright (c) 2020, Blue Liquid Designs
 * @license     http://opensource.org/licenses/gpl-2.0.php GNU Public License
 * @since       1.0
 */
class TokenTest extends WP_UnitTestCase {

	protected $token;
	protected $pdf_path;

	public function setUp() {

		$this->pdf_path = dirname( GFPDF_PDF_PREVIEWER_FILE ) . "/tmp/";

		@mkdir( dirname( $this->pdf_path ) ); //phpcs:disable WordPress.PHP.NoSilencedErrors.Discouraged
		@touch( $this->pdf_path, time(), mktime( null, 2, 0 ) ); //phpcs:disable WordPress.PHP.NoSilencedErrors.Discouraged
		$this->token = new Token( $this->pdf_path );

		parent::setUp(); // TODO: Change the autogenerated stub
	}

	public function tearDown() {
		$file =$this->pdf_path.'12345/12345.pdf';

		if ( is_file( $file ) ) {
			unlink( $file );
			rmdir( dirname( $file ) );
		}

		parent::tearDown(); // TODO: Change the autogenerated stub
	}

	public function test_token() {
		$sample_token = 'OXZNXuePprXrzYkaRH5ckKMtTNxAxyI2Ls+VpeUo2esdlOXoFJh5A6Y4SZci4+mFQW+H+B9mdCuMa9wwZBcrTylHnG4GD6ed4s7tbpKzMbb6UgcaN0U4jxjrNdP/SN2YvA==';

		$token = $this->token->create( [
			1,
			2,
			'12345',
			'12345.pdf',
		] );

		$this->assertSame( strlen( $sample_token ), strlen( $token ) );
	}

	/**
	 * @expectedException Exception
	 */
	public function test_token_missing_parameters() {
		$token = $this->token->create( [
			'12345',
			'12345.pdf',
		] );

		$this->token->validate( $token );
	}

	/**
	 * @expectedException InvalidArgumentException
	 */
	public function test_token_invalid_path() {
		$token = $this->token->create( [
			1,
			1,
			'123452a',
			'123452a.pdf',
		] );

		$this->token->validate( $token );


	}

	/**
	 * @expectedException InvalidArgumentException
	 */
	public function test_token_invalid_file_extension() {
		$token = $this->token->create( [
			1,
			1,
			'test',
			'test.doc',
		] );

		$this->token->validate( $token );
	}
}